CLASS LHC_PURCHASEHEADER DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR PurchaseHeader
        RESULT result,
      CREATE FOR MODIFY
        IMPORTING
          ENTITIES FOR CREATE  PurchaseHeader,
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  PurchaseHeader,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  PurchaseHeader,
      LOCK FOR LOCK
        IMPORTING
          KEYS FOR LOCK  PurchaseHeader,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  PurchaseHeader
        RESULT result,
      CBA_PURCHASEITEM FOR MODIFY
        IMPORTING
          ENTITIES_CBA FOR CREATE  PurchaseHeader\_PurchaseItem,
      RBA_PURCHASEITEM FOR READ
        IMPORTING
          KEYS_RBA FOR READ  PurchaseHeader\_PurchaseItem
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_PURCHASEHEADER IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CREATE.
  ENDMETHOD.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD LOCK.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD CBA_PURCHASEITEM.
  ENDMETHOD.
  METHOD RBA_PURCHASEITEM.
  ENDMETHOD.
ENDCLASS.
CLASS LCL_ZR_PURCHASEHEADER01TP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.
    METHODS:
      FINALIZE REDEFINITION,
      CHECK_BEFORE_SAVE REDEFINITION,
      SAVE REDEFINITION,
      CLEANUP REDEFINITION,
      CLEANUP_FINALIZE REDEFINITION.
ENDCLASS.

CLASS LCL_ZR_PURCHASEHEADER01TP IMPLEMENTATION.
  METHOD FINALIZE.
  ENDMETHOD.
  METHOD CHECK_BEFORE_SAVE.
  ENDMETHOD.
  METHOD SAVE.
  ENDMETHOD.
  METHOD CLEANUP.
  ENDMETHOD.
  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.
ENDCLASS.
